name = "socialtaskhub-auth"
main = "auth/index.js"  # Ensure this file exists
compatibility_date = "2023-12-01"

# Deploy to a Workers.dev subdomain (remove this if using a custom domain)
workers_dev = true

# If using a custom domain, configure routes (Remove this block if not needed)
# [routes]
# pattern = "/api/auth/*"
# zone_name = "socialtaskhub.com"

# Triggers (Optional, if you need scheduled jobs)
[triggers]
crons = []
